### ISSUE TITLE
error with coreutils

### ISSUE THREAD

**Issue by phwuil** [rivy/scoop-bucket#2]
Hi,

When using any command from the `coretuils` package (for instance `date`, `touch`, `tail`, etc.),  I receive the same error message :
```
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x71690000, RegionSize 0x4B0000, State 0x10000
C:\Users\phwuil\scoop\apps\coreutils\current\bin\touch.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
```

I tried to uninstall/clean/reinstall coreutils with no effect.

Thanks !

PS- Windows 10 / 21H1  (19043.1237) / PowerShell 7.1.4 (user or admin)  or CMD

**Comment by rivy** [comment]
Sorry, but you're using the `coreutils` off of [scoop's main bucket](https://github.com/ScoopInstaller/Main) which is old and broken. The coreutils in the bucket I maintain here is based upon the rust busybox-type implementation and working great.

You'll want to re-post this issue on [ScoopInstaller/Main](https://github.com/ScoopInstaller/Main/issues).
